q1 = function(session=session, type=NULL) {
  if(is.null(type)==F){
    title = 'Initial Test Query'
    if(type=='title'){ return(title)}
    description = 'May be deleted later'
    if(type=='description'){ return(description)}
  } else { 

 updateCoverages(session = session,
    nr.importers.incl = 'ALL',
    keep.level = TRUE,
    separate.importer.groups = FALSE,
    current.year.todate = TRUE,
    mast.chapters = c('all'),
    implementers = c('all'),
    importers = c('China'),
    eligible.firms = c('any'),
    in.force.today = 'Any',
    keep.revocation.na = TRUE,
    incl.exporters.strictness = 'ONEPLUS',
    lag.adjustment = '2019-08-17',
    coverage.period = c(2017,2019),
    choose.output = 'share',
    intervention.ids = '',
    implementation.period = c('2015-06-24','2017-08-15'),
    cpc.sectors = c('all'),
    nr.importers = '',
    group.importers = TRUE,
    separate.exporter.groups = FALSE,
    announcement.period = c(NA,NA),
    keep.firms = TRUE,
    keep.implementer = TRUE,
    group.exporters = TRUE,
    keep.importers = TRUE,
    implementation.level = c('any'),
    group.mast = TRUE,
    keep.interventions = TRUE,
    submission.period = c(NA,NA),
    incl.importers.strictness = 'ONEPLUS',
    choose.tradebase = '2017',
    exporters = c('G20'),
    gta.evaluation = c('Red','Amber'),
    keep.hs = TRUE,
    implementer.role = c('Importer','3rd country'),
    keep.exporters = TRUE,
    keep.type = TRUE,
    group.type = TRUE,
    intervention.types = c('Anti-circumvention','Anti-dumping','Anti-subsidy','Capital injection and equity stakes (including bailouts)'),
    affected.flows = '',
    revocation.period = c(NA,NA),
    adjust.for.intra = TRUE,
    hit.brackets = '',
    hs.codes = c('Consumer Good','Capital Good'),
    nr.exporters.incl = 'ALL',
    keep.mast = TRUE,
    nr.exporters = '',
    keep.cpc = TRUE
)}}
